export const LOGIN = 'LOGIN';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';

export const SUCCESS = 'ALERT_SUCCESS';
export const ERROR = 'ALERT_ERROR';
export const CLEAR = 'ALERT_CLEAR';

export const CHECK_EXIST = 'CHECK_EXIST';
export const CHECK_FAILED = 'CHECK_FAILED';
export const CHECK_SUCCEED = 'CHECK_SUCCEED';

export const ADD_LIQUIDITY = 'ADD_LIQUIDITY';
export const ADD_SUCCEED = 'ADD_SUCCEED';
export const ADD_FAILED = 'ADD_FAILED';

export const REMOVE_LIQUIDITY = 'REMOVE_LIQUIDITY';
export const REMOVE_SUCCEED = 'REMOVE_SUCCEED';
export const REMOVE_FAILED = 'REMOVE_FAILED';

export const GET_USER_CAPITAL = 'GET_USER_CAPITAL';
export const GET_USER_CAPITAL_SUCCEED = 'GET_USER_CAPITAL_SUCCEED';
export const GET_USER_CAPITAL_FAILED = 'GET_USER_CAPITAL_FAILED'

export const WITHDRAW = 'WITHDRAW';
export const WITHDRAW_SUCCEED = 'WITHDRAW_SUCCEED';
export const WITHDRAW_FAILED = 'WITHDRAW_FAILED';

export const GET_ALL_TOKEN_STATUS = 'GET_ALL_TOKEN_STATUS';
export const GET_ALL_TOKEN_STATUS_SUCCEED = 'GET_ALL_TOKEN_STATUS_SUCCEED';
export const GET_ALL_TOKEN_STATUS_FAILED = 'GET_ALL_TOKEN_STATUS_FAILED';
export const GET_ALL_TOKEN_ICONS_SUCCEED = 'GET_ALL_TOKEN_ICONS_SUCCEED'

export const DEPOSIT = 'DEPOSIT';
export const DEPOSIT_SUCCEED = 'DEPOSIT_SUCCEED';
export const DEPOSIT_FAILED = 'DEPOSIT_FAILED';
export const GET_L1_CAPITAL_SUCCEED = 'GET_L1_CAPITAL_SUCCEED';
export const GET_L1_CAPITAL_FAILED = 'GET_L1_CAPITAL_FAILED';
